// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: buffer.proto

package buffer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BufferService_AppendRequest_FullMethodName = "/buffer.BufferService/AppendRequest"
	BufferService_PopTop_FullMethodName        = "/buffer.BufferService/PopTop"
)

// BufferServiceClient is the client API for BufferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BufferServiceClient interface {
	AppendRequest(ctx context.Context, in *AppendRequestIn, opts ...grpc.CallOption) (*AppendRequestOut, error)
	PopTop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PopTopOut, error)
}

type bufferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBufferServiceClient(cc grpc.ClientConnInterface) BufferServiceClient {
	return &bufferServiceClient{cc}
}

func (c *bufferServiceClient) AppendRequest(ctx context.Context, in *AppendRequestIn, opts ...grpc.CallOption) (*AppendRequestOut, error) {
	out := new(AppendRequestOut)
	err := c.cc.Invoke(ctx, BufferService_AppendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bufferServiceClient) PopTop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PopTopOut, error) {
	out := new(PopTopOut)
	err := c.cc.Invoke(ctx, BufferService_PopTop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BufferServiceServer is the server API for BufferService service.
// All implementations must embed UnimplementedBufferServiceServer
// for forward compatibility
type BufferServiceServer interface {
	AppendRequest(context.Context, *AppendRequestIn) (*AppendRequestOut, error)
	PopTop(context.Context, *emptypb.Empty) (*PopTopOut, error)
	mustEmbedUnimplementedBufferServiceServer()
}

// UnimplementedBufferServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBufferServiceServer struct {
}

func (UnimplementedBufferServiceServer) AppendRequest(context.Context, *AppendRequestIn) (*AppendRequestOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendRequest not implemented")
}
func (UnimplementedBufferServiceServer) PopTop(context.Context, *emptypb.Empty) (*PopTopOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopTop not implemented")
}
func (UnimplementedBufferServiceServer) mustEmbedUnimplementedBufferServiceServer() {}

// UnsafeBufferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BufferServiceServer will
// result in compilation errors.
type UnsafeBufferServiceServer interface {
	mustEmbedUnimplementedBufferServiceServer()
}

func RegisterBufferServiceServer(s grpc.ServiceRegistrar, srv BufferServiceServer) {
	s.RegisterService(&BufferService_ServiceDesc, srv)
}

func _BufferService_AppendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequestIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BufferServiceServer).AppendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BufferService_AppendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BufferServiceServer).AppendRequest(ctx, req.(*AppendRequestIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _BufferService_PopTop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BufferServiceServer).PopTop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BufferService_PopTop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BufferServiceServer).PopTop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BufferService_ServiceDesc is the grpc.ServiceDesc for BufferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BufferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buffer.BufferService",
	HandlerType: (*BufferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendRequest",
			Handler:    _BufferService_AppendRequest_Handler,
		},
		{
			MethodName: "PopTop",
			Handler:    _BufferService_PopTop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buffer.proto",
}
