// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: buffer.proto

package buffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId     uint64 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Priority     uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	CleaningType string `protobuf:"bytes,4,opt,name=cleaning_type,json=cleaningType,proto3" json:"cleaning_type,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Request) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Request) GetCleaningType() string {
	if x != nil {
		return x.CleaningType
	}
	return ""
}

type AppendBufRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *Request `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *AppendBufRequest) Reset() {
	*x = AppendBufRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendBufRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBufRequest) ProtoMessage() {}

func (x *AppendBufRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBufRequest.ProtoReflect.Descriptor instead.
func (*AppendBufRequest) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{1}
}

func (x *AppendBufRequest) GetReq() *Request {
	if x != nil {
		return x.Req
	}
	return nil
}

type AppendBufResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size   uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AppendBufResponse) Reset() {
	*x = AppendBufResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendBufResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBufResponse) ProtoMessage() {}

func (x *AppendBufResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBufResponse.ProtoReflect.Descriptor instead.
func (*AppendBufResponse) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{2}
}

func (x *AppendBufResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AppendBufResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type PopTopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PopTopRequest) Reset() {
	*x = PopTopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopTopRequest) ProtoMessage() {}

func (x *PopTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopTopRequest.ProtoReflect.Descriptor instead.
func (*PopTopRequest) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{3}
}

type PopTopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *Request `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
}

func (x *PopTopResponse) Reset() {
	*x = PopTopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopTopResponse) ProtoMessage() {}

func (x *PopTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopTopResponse.ProtoReflect.Descriptor instead.
func (*PopTopResponse) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{4}
}

func (x *PopTopResponse) GetReq() *Request {
	if x != nil {
		return x.Req
	}
	return nil
}

type PopBottomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurReq *Request `protobuf:"bytes,1,opt,name=cur_req,json=curReq,proto3" json:"cur_req,omitempty"`
}

func (x *PopBottomRequest) Reset() {
	*x = PopBottomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopBottomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopBottomRequest) ProtoMessage() {}

func (x *PopBottomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopBottomRequest.ProtoReflect.Descriptor instead.
func (*PopBottomRequest) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{5}
}

func (x *PopBottomRequest) GetCurReq() *Request {
	if x != nil {
		return x.CurReq
	}
	return nil
}

type PopBottomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeclinedReq *Request `protobuf:"bytes,1,opt,name=declined_req,json=declinedReq,proto3" json:"declined_req,omitempty"`
	Status      bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PopBottomResponse) Reset() {
	*x = PopBottomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopBottomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopBottomResponse) ProtoMessage() {}

func (x *PopBottomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buffer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopBottomResponse.ProtoReflect.Descriptor instead.
func (*PopBottomResponse) Descriptor() ([]byte, []int) {
	return file_buffer_proto_rawDescGZIP(), []int{6}
}

func (x *PopBottomResponse) GetDeclinedReq() *Request {
	if x != nil {
		return x.DeclinedReq
	}
	return nil
}

func (x *PopBottomResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_buffer_proto protoreflect.FileDescriptor

var file_buffer_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x77, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c,
	0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x35, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x42, 0x75, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x6f, 0x70, 0x54, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x33, 0x0a, 0x0e, 0x50, 0x6f, 0x70, 0x54,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65,
	0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x22, 0x3c, 0x0a,
	0x10, 0x50, 0x6f, 0x70, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x06, 0x63, 0x75, 0x72, 0x52, 0x65, 0x71, 0x22, 0x5f, 0x0a, 0x11, 0x50,
	0x6f, 0x70, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x32, 0x0a, 0x0c, 0x64, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x71,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x64, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xcc, 0x01, 0x0a,
	0x0d, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40,
	0x0a, 0x09, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x66, 0x12, 0x18, 0x2e, 0x62, 0x75,
	0x66, 0x66, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x41,
	0x70, 0x70, 0x65, 0x6e, 0x64, 0x42, 0x75, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x37, 0x0a, 0x06, 0x50, 0x6f, 0x70, 0x54, 0x6f, 0x70, 0x12, 0x15, 0x2e, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x54, 0x6f,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x50, 0x6f, 0x70,
	0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x12, 0x18, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e,
	0x50, 0x6f, 0x70, 0x42, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x70, 0x42, 0x6f, 0x74,
	0x74, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x61, 0x7a, 0x68, 0x65, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_buffer_proto_rawDescOnce sync.Once
	file_buffer_proto_rawDescData = file_buffer_proto_rawDesc
)

func file_buffer_proto_rawDescGZIP() []byte {
	file_buffer_proto_rawDescOnce.Do(func() {
		file_buffer_proto_rawDescData = protoimpl.X.CompressGZIP(file_buffer_proto_rawDescData)
	})
	return file_buffer_proto_rawDescData
}

var file_buffer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_buffer_proto_goTypes = []interface{}{
	(*Request)(nil),           // 0: buffer.Request
	(*AppendBufRequest)(nil),  // 1: buffer.AppendBufRequest
	(*AppendBufResponse)(nil), // 2: buffer.AppendBufResponse
	(*PopTopRequest)(nil),     // 3: buffer.PopTopRequest
	(*PopTopResponse)(nil),    // 4: buffer.PopTopResponse
	(*PopBottomRequest)(nil),  // 5: buffer.PopBottomRequest
	(*PopBottomResponse)(nil), // 6: buffer.PopBottomResponse
}
var file_buffer_proto_depIdxs = []int32{
	0, // 0: buffer.AppendBufRequest.req:type_name -> buffer.Request
	0, // 1: buffer.PopTopResponse.req:type_name -> buffer.Request
	0, // 2: buffer.PopBottomRequest.cur_req:type_name -> buffer.Request
	0, // 3: buffer.PopBottomResponse.declined_req:type_name -> buffer.Request
	1, // 4: buffer.BufferService.AppendBuf:input_type -> buffer.AppendBufRequest
	3, // 5: buffer.BufferService.PopTop:input_type -> buffer.PopTopRequest
	5, // 6: buffer.BufferService.PopBottom:input_type -> buffer.PopBottomRequest
	2, // 7: buffer.BufferService.AppendBuf:output_type -> buffer.AppendBufResponse
	4, // 8: buffer.BufferService.PopTop:output_type -> buffer.PopTopResponse
	6, // 9: buffer.BufferService.PopBottom:output_type -> buffer.PopBottomResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_buffer_proto_init() }
func file_buffer_proto_init() {
	if File_buffer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buffer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendBufRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendBufResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopTopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopTopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopBottomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopBottomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buffer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buffer_proto_goTypes,
		DependencyIndexes: file_buffer_proto_depIdxs,
		MessageInfos:      file_buffer_proto_msgTypes,
	}.Build()
	File_buffer_proto = out.File
	file_buffer_proto_rawDesc = nil
	file_buffer_proto_goTypes = nil
	file_buffer_proto_depIdxs = nil
}
